name: adimeo
recipe: wordpress
config:
  webroot: web
services:
  appserver:
    type: php:8.2
  phpmyadmin:
    type: phpmyadmin
    portforward: true
  mailhog:
    type: mailhog
    portforward: true